[package]
name = "amrust_lib"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "amrust_lib"
path = "src/lib.rs"

[dependencies]
egui = { workspace = true }
anyhow = { workspace = true }
roxmltree = { workspace = true }
log = { workspace = true }
image = { workspace = true, default-features = true }
glam = { workspace = true }
egui_extras = { workspace = true, features = ["default", "image"] }

amrust_3mf = { workspace = true }
amrust_render = { workspace = true }
