[package]
name = "amrust_3mf"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true


description = "3MF (3D Manufacturing Format) file format support"
keywords = ["3MF", "CAD", "slicer", "triangle", "mesh"]
categories = ["encoding", "rendering::data-formats"]

[dependencies]
instant-xml = { workspace = true }
image = { workspace = true, features = ["png"] }
thiserror = { workspace = true }
glam = { workspace = true }
zip = { workspace = true, features = ["deflate"] }

amrust_render = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
collapse = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
pollster = { workspace = true }
nv-flip = { workspace = true }


# [patch.crates-io]
# instant-xml = { git = "https://github.com/djc/instant-xml.git" }
