[package]
name = "amrust"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "AMRUST"
path = "src/main.rs"

[dependencies]
eframe = { workspace = true, features = ["default", "wgpu"] }
egui = { workspace = true }
egui_extras = { workspace = true, features = ["default", "image"] }
egui_logger = { workspace = true }
log = { workspace = true }
pollster = { workspace = true }

amrust_lib = { workspace = true }
