[package]
name = "amrust_render"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
futures-intrusive = { workspace = true }
wgpu = { workspace = true, features = ["spirv"] }
log = { workspace = true }
bytemuck = { workspace = true, features = ["derive"] }
glam = { workspace = true }
image = { workspace = true, default-features = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tinyvec = { workspace = true }


[dev-dependencies]
pollster = { workspace = true }
env_logger = { workspace = true }
nv-flip = { workspace = true }
